@startuml

actor HR as "System Admin"

rectangle Database

rectangle "Population System" {
    usecase UC4 as "Return reports
    on population"

    usecase UCa as "Print Reports"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml